version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cards_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: dilshodlatipov748@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root1234
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
      - "5050:80"
    depends_on:
      - postgres
      - keycloak_postgres
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json

  keycloak_postgres:
    image: postgres:15
    container_name: keycloak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: root1234
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: root1234

      # Admin credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123

      # Import realm on startup
      KC_IMPORT: /opt/keycloak/data/import/realm-export.json

    command:
      - start-dev
      - --import-realm

    volumes:
      - ./config:/opt/keycloak/data/import

    ports:
      - "9090:8080"
    depends_on:
      - keycloak_postgres

volumes:
  postgres_keycloak_data:
  postgres_data:
