spring:
  config:
    activate:
      on-profile: security


crypto:
  rsa:
    public: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl2FxGF7iH3xM2jAp7fnl
      Gu1WvVrotJWj+GEZw4E9Kd4rrnLHUhAdjLkMvguUFmL/LfQXM22U5JFdvat8Hub3
      35UqsNvhwr9GSIY9cVWZ+2HpG+uHbGJD9vMUQjSdV1Pl1YBFRrg69NA0Pu7OSXje
      mEGrtKOX6sNgJ6kNc/PZwpfOTPcQ+WIAIz4C8YRWD+CZODVRgPldl1T5kjoUS7+U
      RfyHz6a8JR9F0tXg1YNFBTOJX0/RLL/4UJMoHYnPmzi+/7KTddQk2/DDBrTfWYW7
      M0t76ugSwHsOHlPWPPy7MYo5j8xlFT2VsOvmGU2UHeiVINLEZJnq2r5cCwc28jR9
      UQIDAQAB
      -----END PUBLIC KEY-----
    private: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEAl2FxGF7iH3xM2jAp7fnlGu1WvVrotJWj+GEZw4E9Kd4rrnLH
      UhAdjLkMvguUFmL/LfQXM22U5JFdvat8Hub335UqsNvhwr9GSIY9cVWZ+2HpG+uH
      bGJD9vMUQjSdV1Pl1YBFRrg69NA0Pu7OSXjemEGrtKOX6sNgJ6kNc/PZwpfOTPcQ
      +WIAIz4C8YRWD+CZODVRgPldl1T5kjoUS7+URfyHz6a8JR9F0tXg1YNFBTOJX0/R
      LL/4UJMoHYnPmzi+/7KTddQk2/DDBrTfWYW7M0t76ugSwHsOHlPWPPy7MYo5j8xl
      FT2VsOvmGU2UHeiVINLEZJnq2r5cCwc28jR9UQIDAQABAoIBAA068S8z1bfyPWZB
      WNzJXx5iGVddy2JDBMxnsiB92lpfJjquIeD4cxiyMJyoduYY+1vpDiEKxf1O/h4e
      T3AE+Ct0hkFkSkAixvH+N38A//7yMPUledW9Zdq+pmnd3tV7yeXFuuhCIDb2vmY0
      qVdPBsdQUAEu3g9gyXXV5szYRlMlHmttDPAzV6JpW1TfRqJ7NiftuxzSWGYT85Gb
      ic7wPXIxhX6+v+i/7+aaLt5oh0wm0TOfz9JRl1GLArRmnMKpX50MHh9jAh7GdUOX
      umVPlO14ID4EbO+td4/SCDOeKWsMfTitbly5/4sXkeYp9nC4d/iQ00KgzWuidGgo
      +TApOIUCgYEAzakR+/E0IBnBTemwsNnoNqgWYDBoDG34YUUKefDgS71+TWuzfLrU
      +aHLHs0OMICmTABN28Xh+nG0JlEHnBBStRWGKRdPTdi0QF0aqoQKBkzkcWnIQXVP
      WymtLwDue9mNfwzfDAsPOlRMqRrZMLyeJT8/+52lkwVmAvdcIS/YDZUCgYEAvG8i
      VMQ7EUShORfYUM34+3UNV55Wmchep87US6MyfNcRWsVfqLGNNcOl5P3KhBnnsnlM
      d5G7t0TzQ9bXXB/Qt964qOtS3BhcvqP4n9qGCBjN9qRyrCL2ApD//zh2vfRPoAiX
      SVKSA5PQnXfaAhJO4wNcSXGvdIqWcC3JWZ9B6c0CgYEAh0UnQRF7eYm3LWoB/7C0
      Hg8c+JOePF6wujnRFDetL+QpiP7IBchVgQQ8N7wkEx7rQp4Il/9mDXZwSauOV8Yc
      wGKx5aEhVlCs7pDOk01Z0p8MutQbFYL1eT7GXF4+flOvz9tFcgRsNa9w5OF17aqC
      UnlxuiwM1dD9MgJFJMb1UqkCgYEAp/CAb33oiu5YplK7JuE725iqCIIE+tAalIKA
      sNzFPYBMZlLse6Oqj9VMQDd0y6Fu36C95v8Khz87dCXBEMkGMymb+GirE5/e4MWw
      639N31+ECSLtVL9f9E+Y6LVBFvDsGlwtwVqG6gtObVmJAjmg9zBiis54qmxtwZL9
      FhQbIa0CgYEAlKvNFfWHT5vxPS+Q+biCHUK4ndI6FrUz89h2RKhPgNm7aIMfK6aU
      aqNTrEzlW9f69vOUog0ljpDRqpq1S1dsjLT0bWT0TQ4fO7bAktzLZU4o8e5BvMzr
      H4H1A+aBrjG+Ceoy8l+sva0Dhow1twYQgxPEBhJznbQ1Kl239IyQ9F8=
      -----END RSA PRIVATE KEY-----
